#!/usr/bin/env bash
ROOT=~/Workspaces/KSP/runtime

if [ -z "$1" ] ; then
	ls -w ${ROOT}
	exit 0
fi

ksp=$1
if [ ! -e ${ROOT}/${ksp} ] ; then
	echo ${ksp} not found!
	exit -1
fi

set MONO_THREADS_PER_CPU=1
ksp=${ROOT}/${ksp}
cd $ksp
open $ksp/KSP.app
