#!/usr/bin/env bash
#
# This file is better visualized configuring a TAB to be 4 spaces width
#
#
#	This file is part of KSP-Hacks (http://ksp.lisias.net/add-ons/KSP-Hacks)
#		© 2018-25 Lisias T : http://lisias.net <support@lisias.net>
#
#	KSP-Hacks is double licensed, as follows:
#		* SKL 1.0 : https://ksp.lisias.net/SKL-1_0.txt
#		* GPL 2.0 : https://www.gnu.org/licenses/gpl-2.0.txt
#
#	And you are allowed to choose the License that better suit your needs.
#
#	KSP-Hacks is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#	You should have received a copy of the SKL Standard License 1.0
#	along with KSP-Hacks. If not, see <https://ksp.lisias.net/SKL-1_0.txt>.
#
#	You should have received a copy of the GNU General Public License 2.0
#	along with KSP-Hacks. If not, see <https://www.gnu.org/licenses/>.

ROOT=~/Workspaces/KSP/runtime

if [ -z "$1" ] ; then
	ls -w ${ROOT}
	exit 0
fi

ksp=$1
if [ ! -e ${ROOT}/${ksp} ] ; then
	echo ${ksp} not found!
	exit -1
fi

set MONO_THREADS_PER_CPU=1
set SSLKEYLOGFILE=~/.SSHKEY.log
ksp=${ROOT}/${ksp}
cd $ksp
open $ksp/KSP.app --args -crash-report-folder ~/temp/ksp
pid=$(ps aux | grep -v grep |grep -i "KSP.app" | awk '{print $2;}')
echo "PID = $pid"
#echo "$(which nettop) -p $pid -L 0 ; rm /tmp/tmp.sh" > /tmp/ksp.tmp.sh ; chmod +x /tmp/ksp.tmp.sh ; open -a Terminal /tmp/ksp.tmp.sh
