#!/usr/bin/env bash
#
# This file is better visualized configuring a TAB to be 4 spaces width
#
#
#	This file is part of KSP-Hacks (http://ksp.lisias.net/add-ons/KSP-Hacks)
#		© 2018-25 Lisias T : http://lisias.net <support@lisias.net>
#
#	KSP-Hacks is double licensed, as follows:
#		* SKL 1.0 : https://ksp.lisias.net/SKL-1_0.txt
#		* GPL 2.0 : https://www.gnu.org/licenses/gpl-2.0.txt
#
#	And you are allowed to choose the License that better suit your needs.
#
#	KSP-Hacks is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#	You should have received a copy of the SKL Standard License 1.0
#	along with KSP-Hacks. If not, see <https://ksp.lisias.net/SKL-1_0.txt>.
#
#	You should have received a copy of the GNU General Public License 2.0
#	along with KSP-Hacks. If not, see <https://www.gnu.org/licenses/>.

ROOT=~/Workspaces/KSP/runtime
POOL=${ROOT}/_pool

if [ -z "$1" ] ; then
	ls -w ${POOL}
	exit 0
fi

ksp=$1
src=$2
target=$3

if [ -z "${target}" ] ; then
	target="${src}"
fi

if [ ${ksp} != "." ] ; then
	ksp=${ROOT}/${ksp}
fi

if [ ! -d "${POOL}/${src}" ] && [ ! -f "${POOL}/${src}" ] ; then
	echo "${POOL}/${src} does not exists!"
	exit -1
fi

if [ -d "${ksp}/GameData/${target}" ] || [ -f "${ksp}/GameData//${target}" ] ; then
	echo "${ksp}/GameData/${target} already exists!"
	exit -2
fi

if [ ! -e ${ksp}/KSP.app ] ; then
	echo "KSP executable not found on ${ksp}!"
	exit -3
fi

ln -s "${POOL}/${src}" "${ksp}/GameData/${target}"
