#!/usr/bin/env bash
ROOT=~/Workspaces/KSP/runtime
POOL=${ROOT}/_pool

if [ -z "$1" ] ; then
	ls -w ${POOL}
	exit 0
fi

ksp=$1
src=$2
target=$3

if [ -z "${target}" ] ; then
	target="${src}"
fi

if [ ${ksp} != "." ] ; then
	ksp=${ROOT}/${ksp}
fi

if [ ! -d "${POOL}/${src}" ] && [ ! -f "${POOL}/${src}" ] ; then
	echo "${POOL}/${src} does not exists!"
	exit -1
fi

if [ -d "${ksp}/GameData/${target}" ] || [ -f "${ksp}/GameData//${target}" ] ; then
	echo "${ksp}/GameData/${target} already exists!"
	exit -2
fi

if [ ! -e ${ksp}/KSP.app ] ; then
	echo "KSP executable not found on ${ksp}!"
	exit -3
fi

ln -s "${POOL}/${src}" "${ksp}/GameData/${target}"
